info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:19:05.765Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:19:05.841Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:19:15.169Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:19:15.216Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:19:36.541Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:19:36.578Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:20:06.662Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:20:06.708Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:20:36.345Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:20:36.394Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:20:53.623Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:20:53.660Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:21:34.701Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:21:34.740Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (C:\Users\srikanth naidu\Fundoo-Notes\src\services\/user.service.js:35:13)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-13T04:22:06.195Z"}
error: 
    status - 500 
    message - Error: Already Exist EmailId
    at _callee$ (C:\Users\srikanth naidu\Fundoo-Notes\src\services\/user.service.js:16:11)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/Register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-13T04:22:29.613Z"}
error: 
    status - 500 
    message - TypeError: UserService.forgotPassword is not a function
    at _callee3$ (C:\Users\srikanth naidu\Fundoo-Notes\src\controllers\/user.controller.js:49:34)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at forgotPassword (C:\Users\srikanth naidu\Fundoo-Notes\src\controllers\/user.controller.js:47:28)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/forgotpwd 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-13T04:27:17.453Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:28:25.359Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:28:25.395Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:28:38.000Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:28:38.104Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:29:10.875Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:29:10.918Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:30:32.452Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:30:32.497Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:30:47.799Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:30:47.843Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:31:02.922Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:31:02.974Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:32:28.016Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:32:28.070Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:32:39.830Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:32:39.866Z"}
error: 
    status - 500 
    message - TypeError: UserService.forgotPassword is not a function
    at _callee3$ (C:\Users\srikanth naidu\Fundoo-Notes\src\controllers\/user.controller.js:49:34)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at forgotPassword (C:\Users\srikanth naidu\Fundoo-Notes\src\controllers\/user.controller.js:47:28)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\index.js:280:10)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\raw-body\index.js:231:16)
    at done (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/forgotpwd 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-13T04:32:43.590Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:33:01.615Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:33:01.647Z"}
error: 
    status - 500 
    message - ReferenceError: env is not defined
    at _callee3$ (C:\Users\srikanth naidu\Fundoo-Notes\src\services\/user.service.js:50:78)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/forgotpwd 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-13T04:33:03.631Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:36:34.872Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:36:34.902Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:38:58.302Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:38:58.329Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:39:06.446Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:39:06.484Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:39:15.414Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:39:15.458Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T04:39:33.107Z"}
info: Connected to the database. {"timestamp":"2023-02-13T04:39:33.143Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T05:02:41.031Z"}
info: Connected to the database. {"timestamp":"2023-02-13T05:02:41.063Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/resetpwd 
      method - PUT 
      IP - ::1
     {"timestamp":"2023-02-13T05:04:42.056Z"}
error: 
    status - 500 
    message - Error: data must be a string or Buffer and salt must either be a salt string or a number of rounds
    at Object.hashSync (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\bcrypt\bcrypt.js:95:15)
    at _callee4$ (C:\Users\srikanth naidu\Fundoo-Notes\src\services\/user.service.js:62:23)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.resetPassword (C:\Users\srikanth naidu\Fundoo-Notes\src\services\/user.service.js:59:27)
    at _callee4$ (C:\Users\srikanth naidu\Fundoo-Notes\src\controllers\/user.controller.js:65:34)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at resetPassword (C:\Users\srikanth naidu\Fundoo-Notes\src\controllers\/user.controller.js:63:27)
    at Layer.handle [as handle_request] (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (C:\Users\srikanth naidu\Fundoo-Notes\src\middlewares\/auth.middleware.js:27:5)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/resetpwd 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-13T05:05:17.730Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T05:06:16.790Z"}
info: Connected to the database. {"timestamp":"2023-02-13T05:06:16.821Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T05:06:44.225Z"}
info: Connected to the database. {"timestamp":"2023-02-13T05:06:44.254Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T05:08:31.921Z"}
info: Connected to the database. {"timestamp":"2023-02-13T05:08:31.950Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T05:08:39.806Z"}
info: Connected to the database. {"timestamp":"2023-02-13T05:08:39.841Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (C:\Users\srikanth naidu\Fundoo-Notes\src\services\/user.service.js:36:13)
    at tryCatch (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\srikanth naidu\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/Login 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-13T05:09:10.752Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-13T05:11:33.101Z"}
info: Connected to the database. {"timestamp":"2023-02-13T05:11:33.131Z"}
